// Regenerates a tests/fixtures/public-tailwind stylesheet from one of the input files beside this
// script using the real Tailwind compiler, so the page-styles tests run against output Tailwind
// actually produced rather than a hand-written approximation of it.
//
//     node tests/fixtures/tailwind/build.mjs
//     node tests/fixtures/tailwind/build.mjs --input=input-colormix.css --output=../public-tailwind/build/assets/app-tailwind-colormix.css
//
// Options, all optional and relative to this script's own directory:
//
//     --input=<file>          the stylesheet to compile (default input.css)
//     --output=<file>         where to write the compiled CSS (default ../public-tailwind/build/assets/app-tailwind.css)
//     --node-modules=<dir>    where to resolve @tailwindcss/node from (default the host application's,
//                             six levels up)
//
// The Vite manifest names the default output only, since that is the entry the page-styles feature
// tests resolve through it; every other output is a fixture the unit tests read by path, so the
// manifest is left alone when one is generated.
//
// The generated CSS and manifest are committed: they are test inputs, and the suite must not
// depend on Node being installed.

import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The value of a --key=value argument, or null when it was not given.
 */
const option = (key) => {
    const argument = process.argv.slice(2).find((value) => value.startsWith(`--${key}=`));

    return argument === undefined ? null : argument.slice(key.length + 3);
};

const nodeModules = resolve(option('node-modules') ?? resolve(here, '../../../../../../node_modules'));
const require = createRequire(resolve(nodeModules, 'noop.js'));

const { compile, optimize } = await import(require.resolve('@tailwindcss/node'));
const version = require('tailwindcss/package.json').version;

const input = resolve(here, option('input') ?? 'input.css');
const defaultOutput = resolve(here, '../public-tailwind/build/assets/app-tailwind.css');
const output = resolve(here, option('output') ?? defaultOutput);
const source = await readFile(input, 'utf8');

const compiler = await compile(source, { base: here, from: input, onDependency: () => {} });

// Every candidate a fixture needs is declared through `@source inline(...)` in its input, so the
// build needs no scanned candidates of its own.
const built = compiler.build([]);
const css = `/*! tailwindcss v${version} | generated by tests/fixtures/tailwind/build.mjs from ${input.slice(here.length + 1)} */\n${optimize(built, { minify: true }).code}`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, css);

if (output === defaultOutput) {
    await writeFile(
        resolve(dirname(output), '../manifest.json'),
        `${JSON.stringify({ 'resources/css/app.css': { file: 'assets/app-tailwind.css', src: 'resources/css/app.css', isEntry: true } }, null, 4)}\n`,
    );
}

console.log(`wrote ${css.length} bytes of Tailwind ${version} output to ${output}`);
