// Regenerates tests/fixtures/public-tailwind3 with the real Tailwind CSS 3 compiler, so the
// Tailwind 3 driver's tests run against output Tailwind actually produced rather than a hand-written
// approximation of it.
//
//     cd tests/fixtures/tailwind3 && npm install && npm run build
//
// The same result by hand, from this directory:
//
//     npx tailwindcss -c tailwind.config.cjs -i input.css -o ../public-tailwind3/build/assets/app-tailwind3.css --minify
//
// The generated CSS and manifest are committed: they are test inputs, and the suite must not depend
// on Node being installed. node_modules and the package lock stay out of the repository.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const postcss = require('postcss');
const tailwindcss = require('tailwindcss');
const version = require('tailwindcss/package.json').version;

const input = resolve(here, 'input.css');
const output = resolve(here, '../public-tailwind3/build/assets/app-tailwind3.css');
const source = await readFile(input, 'utf8');

const result = await postcss([tailwindcss(resolve(here, 'tailwind.config.cjs'))]).process(source, { from: input, to: output });

// Tailwind 3's own `--minify` runs cssnano through lightningcss when available; Vite runs esbuild.
// The walk is whitespace-agnostic, so either is a faithful fixture; this keeps it at the shape the
// CLI produces by using the same minifier Tailwind ships with when it is installed, and falls back to
// the unminified output otherwise (documented in the banner so a reader knows which one they have).
let css = result.css;
let minifier = 'unminified';

try {
    const { transform } = require('lightningcss');
    css = Buffer.from(transform({ filename: output, code: Buffer.from(css), minify: true }).code).toString();
    minifier = 'lightningcss';
} catch {
    // lightningcss is Tailwind 3's optional dependency; without it the fixture is simply not minified.
}

const banner = `/*! tailwindcss v${version} | ${minifier} | generated by tests/fixtures/tailwind3/build.mjs from input.css */\n`;

await mkdir(dirname(output), { recursive: true });
await writeFile(output, banner + css);
await writeFile(
    resolve(dirname(output), '../manifest.json'),
    `${JSON.stringify({ 'resources/css/app.css': { file: 'assets/app-tailwind3.css', src: 'resources/css/app.css', isEntry: true } }, null, 4)}\n`,
);

console.log(`wrote ${banner.length + css.length} bytes of Tailwind ${version} output (${minifier}) to ${output}`);
